# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Spektre Labs / Lauri Rainio
"""
Autogenerate per-kernel docs/vNN/README.md pages for v71..v100.

For each `src/vN/creation_os_vN.c` we:
  * extract the leading /* ... */ header comment,
  * strip leading asterisks and whitespace,
  * derive a human-friendly title from the first non-SPDX line,
  * emit a docs/vN/README.md with: title, short description,
    code link, self-test command, and the first ~30 lines of the
    source header verbatim as an implementation excerpt.

This is mechanical and deterministic.  Re-running the script is
idempotent: it will overwrite any file it has previously written with
the marker comment below; hand-authored `docs/vN/README.md` files
without the marker are left alone.

Marker:  <!-- v111: autogenerated by tools/docs/generate_kernel_pages.py -->
"""

from __future__ import annotations

import os
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MARK = "<!-- v111: autogenerated by tools/docs/generate_kernel_pages.py -->"

KERNELS = {
    # pre-derived titles for kernels whose header doesn't self-label cleanly
    71: "σ-Wormhole",                72: "σ-Neuron",
    73: "σ-Reservoir",               74: "σ-Liquid",
    76: "σ-License Attestation",     77: "σ-Attestation Chain",
    78: "σ-Pointer",                 79: "σ-Cortex Primitives",
    80: "σ-Cortex Self-Test",        81: "σ-Cortex Extension",
    82: "σ-Cortex Benchmarks",       83: "σ-Cortex Receipt",
    84: "σ-Cortex Schema",           85: "σ-Cortex Fabric",
    86: "σ-Cortex Intellect",        87: "σ-Cortex Reasoning",
    88: "σ-Cortex Generation",       89: "σ-Cortex Hypervector",
    90: "σ-Hierarchical",            91: "σ-Hierarchical Schema EMA",
    92: "σ-Hierarchical Compose",    93: "σ-Hierarchical Stack",
    94: "σ-Hierarchical Proof",      95: "σ-Hierarchical Release",
    96: "σ-Attractor",               97: "σ-Attractor Stability",
    98: "σ-Attractor Convergence",   99: "σ-Attractor Phase",
   100: "σ-Hyena",
}


def _extract_header(c_path: Path) -> tuple[str, str]:
    """Return (title, raw_comment_block) from a C source file."""
    text = c_path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"/\*(.*?)\*/", text, flags=re.S)
    body = m.group(1) if m else ""
    # strip leading asterisks
    clean = re.sub(r"^\s*\*\s?", "", body, flags=re.M).strip()
    # find the first "Creation OS vN — XYZ" line, or use the dict
    title = None
    for line in clean.split("\n"):
        line = line.strip()
        if not line or line.startswith("SPDX-"):
            continue
        tm = re.match(r"Creation\s+OS\s+v\d+\s*[—\-:–]\s*(.+?)$",
                      line, flags=re.I)
        if tm:
            raw = tm.group(1).strip(" -—.:;")
            # trim trailing " self-test driver" / " self-test + microbench driver"
            raw = re.sub(r"\s*[:\-]?\s*standalone\s+self-test.*$", "", raw, flags=re.I)
            raw = re.sub(r"\s*[:\-]?\s*self-test\b.*$", "", raw, flags=re.I)
            title = raw.strip(" -—.:;")
            break
        break
    if not title:
        title = ""
    return title, clean


def generate_one(n: int) -> Path | None:
    src = REPO / f"src/v{n}/creation_os_v{n}.c"
    if not src.exists():
        return None
    title_guess, header = _extract_header(src)
    title = title_guess or KERNELS.get(n, f"Kernel v{n}")
    out_dir = REPO / f"docs/v{n}"
    out_path = out_dir / "README.md"
    # don't clobber hand-authored doc pages (no marker)
    if out_path.exists():
        try:
            existing = out_path.read_text(encoding="utf-8")
        except OSError:
            existing = ""
        if MARK not in existing:
            return None
    out_dir.mkdir(parents=True, exist_ok=True)

    # short abstract: first paragraph of the header (up to blank line),
    # skipping SPDX and the "Creation OS vN — …" banner line.
    abstract_lines: list[str] = []
    banner_seen = False
    for line in header.split("\n"):
        stripped = line.strip()
        if stripped.startswith("SPDX-"):
            continue
        if stripped.startswith("Creation OS v"):
            banner_seen = True
            continue
        if stripped == "":
            if abstract_lines:
                break
            continue
        abstract_lines.append(line.rstrip())
        if banner_seen and len(abstract_lines) >= 12:
            break
    abstract = "\n".join(abstract_lines).strip()
    if len(abstract) > 800:
        abstract = abstract[:800].rsplit(" ", 1)[0] + " …"

    # self-test command probe: check-vN target exists in Makefile
    mk = (REPO / "Makefile").read_text(encoding="utf-8", errors="replace")
    has_check = f"\ncheck-v{n}:" in mk or f"^check-v{n}:" in mk
    check_cmd = f"make check-v{n}" if has_check else f"(self-test dispatched via standalone-v{n} if present)"

    # file list — whatever lives in src/vN/
    src_dir = REPO / f"src/v{n}"
    src_files = sorted(p.relative_to(REPO) for p in src_dir.iterdir() if p.is_file())
    src_listing = "\n".join(f"- `{p}`" for p in src_files)

    md = []
    md.append(MARK)
    md.append(f"# v{n} — {title}")
    md.append("")
    md.append(f"Canonical directory: [`src/v{n}/`]({'../../src/' + f'v{n}/'}).")
    md.append("")
    md.append("## Abstract")
    md.append("")
    md.append(abstract if abstract else
              f"v{n} kernel — see source header for the authoritative description.")
    md.append("")
    md.append("## Source")
    md.append("")
    md.append(src_listing or "_(no source files enumerated)_")
    md.append("")
    md.append("## Self-test")
    md.append("")
    md.append("```bash")
    md.append(check_cmd)
    md.append("```")
    md.append("")
    md.append("## Relation to the σ-stack")
    md.append("")
    md.append("Layer membership (cf. `docs/AGI_ARCHITECTURE.md`):\n")
    md.append(_layer_hint(n))
    md.append("")
    md.append("## Source-header excerpt")
    md.append("")
    md.append("```c")
    md.append("\n".join(src.read_text(encoding="utf-8").splitlines()[:35]))
    md.append("```")
    md.append("")
    out_path.write_text("\n".join(md), encoding="utf-8")
    return out_path


def _layer_hint(n: int) -> str:
    if 71 <= n <= 79:
        return "- Layer 2 (Generation) support kernels: σ-Wormhole, σ-Neuron, σ-Reservoir, σ-Liquid, σ-Pointer, σ-License."
    if 80 <= n <= 89:
        return "- Layer 3–4 (σ-Governance + Reasoning) — σ-Cortex primitives, benchmarks, schemas, and fabric/intellect wiring."
    if 90 <= n <= 95:
        return "- Layer 3 (σ-Governance) — σ-Hierarchical: EMA convergence, schema compose, free-energy accumulation, proof and release bundle."
    if 96 <= n <= 99:
        return "- Layer 4 (Reasoning) — σ-Attractor: stability, convergence, phase-portrait visualisations."
    if n == 100:
        return "- Layer 2–3 (Generation + σ-Governance) — σ-Hyena: the 40-kernel closer, σ-governed long-context sequence scan."
    return "- see AGI_ARCHITECTURE.md §2–§4."


def main() -> int:
    wrote = 0
    skipped = 0
    for n in range(71, 101):
        r = generate_one(n)
        if r is None:
            skipped += 1
        else:
            wrote += 1
    print(f"generate_kernel_pages: wrote {wrote}, skipped {skipped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
