/* SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (c) 2026 Spektre Labs / Lauri Rainio
 *
 * v137 σ-Compile — implementation.
 */
#include "compile.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ================================================================
 * Reference (interpreted) gate.  Branchless OR of compares over
 * a runtime-provided threshold vector.
 * ============================================================= */
int cos_v137_interpreted_gate(const float tau[COS_V137_CHANNELS],
                              const float ch [COS_V137_CHANNELS]) {
    int deny = 0;
    for (int i = 0; i < COS_V137_CHANNELS; ++i)
        deny |= (ch[i] > tau[i]);
    return deny;
}

/* Embedded "compiled" gate specialised for τ = 0.50 on every
 * channel.  This mirrors exactly what cos_v137_emit_source would
 * write for that profile — no loads, all literals. */
int cos_v137_example_compiled_gate(const float ch[COS_V137_CHANNELS]) {
    return
        (ch[0] > 0.50f) | (ch[1] > 0.50f) |
        (ch[2] > 0.50f) | (ch[3] > 0.50f) |
        (ch[4] > 0.50f) | (ch[5] > 0.50f) |
        (ch[6] > 0.50f) | (ch[7] > 0.50f);
}

/* ================================================================
 * Generator: emit a specialised decision tree as C source.
 * ============================================================= */
int cos_v137_emit_source(const float tau[COS_V137_CHANNELS],
                         const char *path) {
    FILE *fp = path ? fopen(path, "w") : stdout;
    if (!fp) return -1;
    fprintf(fp,
        "/* Generated by v137 σ-compile.  Do not edit by hand. */\n"
        "#include <stdint.h>\n\n"
        "/* AOT-specialised σ-gate — branchless OR of compares. */\n"
        "int cos_v137_compiled_gate(const float ch[8]) {\n"
        "    return\n");
    for (int i = 0; i < COS_V137_CHANNELS; ++i) {
        fprintf(fp, "        (ch[%d] > %.6ff)%s\n",
                i, (double)tau[i],
                i + 1 < COS_V137_CHANNELS ? " |" : ";");
    }
    fprintf(fp, "}\n");
    if (path) fclose(fp);
    return 0;
}

/* ================================================================
 * Benchmarks.  clock_gettime is POSIX; inputs cycle through the
 * provided vectors to defeat the compiler's constant folding on
 * small loops, and the caller XORs the accumulator so -O3 cannot
 * eliminate the calls.
 * ============================================================= */

static double ts_diff_ns(const struct timespec *a,
                         const struct timespec *b) {
    return (double)(b->tv_sec  - a->tv_sec) * 1e9
         + (double)(b->tv_nsec - a->tv_nsec);
}

double cos_v137_bench_interpreted(const float tau[COS_V137_CHANNELS],
                                  const float *vectors, int n_vectors,
                                  int iters, uint64_t *out_checksum) {
    if (!tau || !vectors || n_vectors <= 0 || iters <= 0) return -1.0;
    uint64_t acc = 0;
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (int i = 0; i < iters; ++i) {
        const float *v = vectors + (i % n_vectors) * COS_V137_CHANNELS;
        acc ^= (uint64_t)cos_v137_interpreted_gate(tau, v) << (i & 31);
    }
    clock_gettime(CLOCK_MONOTONIC, &t1);
    if (out_checksum) *out_checksum ^= acc;
    return ts_diff_ns(&t0, &t1) / (double)iters;
}

double cos_v137_bench_compiled(const float *vectors, int n_vectors,
                               int iters, uint64_t *out_checksum) {
    if (!vectors || n_vectors <= 0 || iters <= 0) return -1.0;
    uint64_t acc = 0;
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (int i = 0; i < iters; ++i) {
        const float *v = vectors + (i % n_vectors) * COS_V137_CHANNELS;
        acc ^= (uint64_t)cos_v137_example_compiled_gate(v) << (i & 31);
    }
    clock_gettime(CLOCK_MONOTONIC, &t1);
    if (out_checksum) *out_checksum ^= acc;
    return ts_diff_ns(&t0, &t1) / (double)iters;
}

/* ================================================================
 * Self-test
 * ============================================================= */

#define _CHECK(cond, msg) do { \
    if (!(cond)) { \
        fprintf(stderr, "v137 self-test FAIL: %s (line %d)\n", \
                (msg), __LINE__); return 1; \
    } \
} while (0)

int cos_v137_self_test(void) {
    const float tau[8] = {0.50f, 0.50f, 0.50f, 0.50f,
                          0.50f, 0.50f, 0.50f, 0.50f};

    /* --- A. Semantic equivalence ------------------------------- */
    fprintf(stderr, "check-v137: interpreted ≡ compiled on default profile\n");
    float vecs[8][8] = {
        {0.1f,0.1f,0.1f,0.1f, 0.1f,0.1f,0.1f,0.1f},   /* emit */
        {0.1f,0.1f,0.1f,0.1f, 0.1f,0.1f,0.1f,0.9f},   /* abstain */
        {0.6f,0.1f,0.1f,0.1f, 0.1f,0.1f,0.1f,0.1f},   /* abstain ch0 */
        {0.4f,0.4f,0.4f,0.4f, 0.4f,0.4f,0.4f,0.4f},   /* all < τ emit */
        {0.49f,0.49f,0.49f,0.49f, 0.49f,0.49f,0.49f,0.49f},
        {0.51f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.0f},
        {0.0f,0.0f,0.0f,0.0f, 0.0f,0.0f,0.0f,0.51f},
        {0.2f,0.3f,0.4f,0.49f, 0.48f,0.47f,0.46f,0.45f},
    };
    for (int i = 0; i < 8; ++i) {
        int a = cos_v137_interpreted_gate(tau, vecs[i]);
        int b = cos_v137_example_compiled_gate(vecs[i]);
        _CHECK(a == b, "semantic equivalence");
    }

    /* --- B. Emit source shape ---------------------------------- */
    fprintf(stderr, "check-v137: emit source shape\n");
    const char *out = "/tmp/cos_v137_gen.c";
    _CHECK(cos_v137_emit_source(tau, out) == 0, "emit source");
    FILE *fp = fopen(out, "r"); _CHECK(fp, "open emitted");
    char buf[2048]; size_t r = fread(buf, 1, sizeof buf - 1, fp);
    buf[r] = 0; fclose(fp);
    _CHECK(strstr(buf, "cos_v137_compiled_gate") != NULL, "function name");
    _CHECK(strstr(buf, "(ch[0] > 0.500000f)") != NULL, "literal threshold");
    _CHECK(strstr(buf, ";") != NULL, "terminator");

    /* --- C. Latency benchmark --------------------------------- *
     * 2M iterations through a 32-vector working set.  We assert
     * only the *absolute* ceiling — 500 ns/call — which is the
     * spec's target for the σ-layer.  The v137.0 claim is "both
     * paths are safely under the target, and the specialised path
     * emits well-formed C that the host toolchain can lower".  A
     * guaranteed relative speedup over interpreted is a v137.1
     * follow-up: on modern ARM/x86 the interpreted gate is already
     * auto-vectorised by $(CC) -O3 to SIMD compares, so the
     * benefit of AOT specialisation is mostly felt when linked
     * into a larger σ-pipeline (no function-pointer dispatch, no
     * τ-table prefetch, constant folding across callers) — a
     * setting v137.0 does not exercise inside a single binary.  */
    fprintf(stderr, "check-v137: latency benchmark (2M iters)\n");
    float pool[32 * 8];
    for (int i = 0; i < 32 * 8; ++i)
        pool[i] = (float)(i & 7) * 0.10f;
    uint64_t ck = 0;
    const int iters = 2000000;
    double ns_int = cos_v137_bench_interpreted(tau, pool, 32, iters, &ck);
    double ns_cmp = cos_v137_bench_compiled   (     pool, 32, iters, &ck);
    fprintf(stderr, "  interpreted = %.2f ns/call,  compiled = %.2f ns/call\n",
            ns_int, ns_cmp);
    _CHECK(ns_int > 0 && ns_cmp > 0, "bench ran");
    _CHECK(ns_int < 500.0, "interpreted ≤ 500 ns/call (spec target)");
    _CHECK(ns_cmp < 500.0, "compiled    ≤ 500 ns/call (spec target)");

    fprintf(stderr, "  (ck=%llu to defeat DCE)\n",
            (unsigned long long)ck);
    fprintf(stderr, "check-v137: OK (semantic + emit + latency ≤ 500 ns/call)\n");
    return 0;
}
