/*  SPDX-License-Identifier: LicenseRef-SCSL-1.0 OR AGPL-3.0-only
 *  SPDX-Copyright-Identifier: 2024-2026 Lauri Elias Rainio · Spektre Labs Oy
 *  Source:        https://github.com/spektre-labs/creation-os-kernel
 *  Website:       https://spektrelabs.org
 *  Commercial:    spektre.labs@proton.me
 *  License docs:  LICENSE · LICENSE-SCSL-1.0.md · LICENSE-AGPL-3.0.txt
 *
 *  src/license_kernel/license_attest.c
 *  --------------------------------------------------------------------
 *  License Attestation Kernel — implementation. See the header for
 *  the API contract and SCSL-1.0 §11 mapping.
 *
 *  Hot path: libc-only. SHA-256 round is straight FIPS-180-4. No
 *  malloc, no heap, no TLS, no global writeable state outside of
 *  the static round constants. Receipts render into caller-provided
 *  buffers.
 */

#include "license_attest.h"
#include "crypto/sha256.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>

/* ── pinned canonical SHA-256 of LICENSE-SCSL-1.0.md ───────────── */
/* This literal is regenerated by `make license-pin` from
 * LICENSE.sha256. Keep in sync. */
const char spektre_license_sha256_hex[65] =
    "3faa37ece42aa1836b41e53fc084c9a905f87286123524dda0a0632b81e8f319";

const uint8_t spektre_license_sha256_bin[32] = {
    0x3f,0xaa,0x37,0xec, 0xe4,0x2a,0xa1,0x83,
    0x6b,0x41,0xe5,0x3f, 0xc0,0x84,0xc9,0xa9,
    0x05,0xf8,0x72,0x86, 0x12,0x35,0x24,0xdd,
    0xa0,0xa0,0x63,0x2b, 0x81,0xe8,0xf3,0x19
};

/* ── 1. SHA-256 — delegated to src/crypto/sha256.c ─────────────── */

void spektre_sha256_init(spektre_sha256_ctx_t *ctx)
{
    cos_sha256_init(ctx);
}

void spektre_sha256_update(spektre_sha256_ctx_t *ctx, const void *data,
                           size_t len)
{
    cos_sha256_update(ctx, data, len);
}

void spektre_sha256_final(spektre_sha256_ctx_t *ctx, uint8_t out[32])
{
    cos_sha256_final(ctx, out);
}

void spektre_sha256(const void *data, size_t len, uint8_t out[32])
{
    cos_sha256((const uint8_t *)data, len, out);
}

void spektre_hex_lower(const uint8_t in[32], char out[65]) {
    static const char H[16] = "0123456789abcdef";
    for (int i = 0; i < 32; ++i) {
        out[i*2 + 0] = H[(in[i] >> 4) & 0xF];
        out[i*2 + 1] = H[ in[i]       & 0xF];
    }
    out[64] = 0;
}

int spektre_ct_memcmp(const void *a, const void *b, size_t n) {
    const uint8_t *pa = (const uint8_t *)a;
    const uint8_t *pb = (const uint8_t *)b;
    uint8_t diff = 0;
    for (size_t i = 0; i < n; ++i) {
        diff |= (uint8_t)(pa[i] ^ pb[i]);
    }
    return (int)diff;
}

/* ── 2. License attestation ────────────────────────────────────── */

static int hash_file(const char *path, uint8_t out[32]) {
    FILE *f = fopen(path, "rb");
    if (!f) return -1;
    spektre_sha256_ctx_t ctx;
    spektre_sha256_init(&ctx);
    uint8_t buf[8192];
    size_t n;
    while ((n = fread(buf, 1, sizeof buf, f)) > 0) {
        spektre_sha256_update(&ctx, buf, n);
    }
    int err = ferror(f);
    fclose(f);
    if (err) return -1;
    spektre_sha256_final(&ctx, out);
    return 0;
}

int spektre_license_verify(const char *license_path) {
    /* Sanity: the pinned hash buffer must itself be 32 valid bytes. */
    if (sizeof spektre_license_sha256_bin != 32) return -3;

    const char *try_paths[5];
    int n = 0;
    if (license_path) {
        try_paths[n++] = license_path;
    }
    try_paths[n++] = "./LICENSE-SCSL-1.0.md";
    try_paths[n++] = "../LICENSE-SCSL-1.0.md";
    const char *env = getenv("SPEKTRE_LICENSE_PATH");
    if (env && *env) try_paths[n++] = env;
    try_paths[n++] = NULL;

    uint8_t got[32];
    for (int i = 0; try_paths[i]; ++i) {
        if (hash_file(try_paths[i], got) == 0) {
            if (spektre_ct_memcmp(got, spektre_license_sha256_bin, 32) == 0) {
                return 0;
            }
            return -2;  /* tampered */
        }
    }
    return -1;          /* missing */
}

int spektre_license_bundle_verify(const char *repo_root) {
    static const char *files[] = {
        "LICENSE", "LICENSE-SCSL-1.0.md", "LICENSE-AGPL-3.0.txt",
        "NOTICE", "COMMERCIAL_LICENSE.md", "CLA.md", "LICENSE.sha256",
        NULL
    };
    char path[1024];
    for (int i = 0; files[i]; ++i) {
        if (repo_root && *repo_root) {
            snprintf(path, sizeof path, "%s/%s", repo_root, files[i]);
        } else {
            snprintf(path, sizeof path, "./%s", files[i]);
        }
        FILE *f = fopen(path, "rb");
        if (!f) return -1;
        fclose(f);
    }
    return spektre_license_verify(NULL);
}

/* ── 3. Receipt envelope ───────────────────────────────────────── */

static size_t bytes_to_hex(const uint8_t *src, size_t n,
                           char *dst, size_t cap) {
    static const char H[16] = "0123456789abcdef";
    if (cap < n * 2 + 1) return 0;
    for (size_t i = 0; i < n; ++i) {
        dst[i*2 + 0] = H[(src[i] >> 4) & 0xF];
        dst[i*2 + 1] = H[ src[i]       & 0xF];
    }
    dst[n*2] = 0;
    return n * 2;
}

int spektre_receipt_render(const spektre_receipt_t *r,
                           char *out, size_t cap) {
    if (!r || !out || cap < 256) return -1;

    char ts[64];
    time_t now;
    if (r->emitted_at_ns) {
        now = (time_t)(r->emitted_at_ns / 1000000000ull);
    } else {
        time(&now);
    }
    struct tm tm_utc;
#if defined(_WIN32)
    gmtime_s(&tm_utc, &now);
#else
    gmtime_r(&now, &tm_utc);
#endif
    strftime(ts, sizeof ts, "%Y-%m-%dT%H:%M:%SZ", &tm_utc);

    char bits_hex[1024] = {0};
    if (r->kernel_bits && r->kernel_bits_n &&
        r->kernel_bits_n * 2 + 1 <= sizeof bits_hex) {
        bytes_to_hex(r->kernel_bits, r->kernel_bits_n,
                     bits_hex, sizeof bits_hex);
    }

    int written = snprintf(out, cap,
        "{"
        "\"license\":\"%s\","
        "\"license_sha256\":\"%s\","
        "\"copyright\":\"%s\","
        "\"source\":\"%s\","
        "\"commit\":\"%s\","
        "\"emitted_at\":\"%s\","
        "\"kernel\":{"
            "\"id\":\"%s\","
            "\"verdict\":\"%s\","
            "\"bits\":\"%s\""
        "}"
        "}\n",
        SPEKTRE_LICENSE_SPDX,
        spektre_license_sha256_hex,
        SPEKTRE_COPYRIGHT_LINE,
        SPEKTRE_SOURCE_URL,
        r->commit_sha     ? r->commit_sha     : "0000000000000000000000000000000000000000",
        ts,
        r->kernel_id      ? r->kernel_id      : "unknown",
        r->kernel_verdict ? r->kernel_verdict : "ABSTAIN",
        bits_hex);

    if (written < 0 || (size_t)written >= cap) return -1;
    return written;
}

int spektre_receipt_print(const spektre_receipt_t *r) {
    char buf[1536];
    int n = spektre_receipt_render(r, buf, sizeof buf);
    if (n < 0) return -1;
    if (fwrite(buf, 1, (size_t)n, stdout) != (size_t)n) return -1;
    fflush(stdout);
    return 0;
}

void spektre_receipt_hash(const char *receipt_json, uint8_t out[32]) {
    spektre_sha256(receipt_json, strlen(receipt_json), out);
}

/* ── 4. Anti-tamper guard ──────────────────────────────────────── */

int spektre_license_guard(void) {
    int rc = spektre_license_verify(NULL);
    if (rc == 0) return 0;

    const char *soft = getenv("SPEKTRE_LICENSE_SOFT");
    int hard = !(soft && soft[0] == '1');

    const char *why =
        (rc == -1) ? "license file missing"
      : (rc == -2) ? "license file tampered (SHA-256 mismatch)"
      : (rc == -3) ? "pinned-hash buffer is corrupt"
      :              "unknown";

    fprintf(stderr,
        "spektre-license-guard: BREACH (rc=%d, %s)\n"
        "  expected sha256: %s\n"
        "  see SCSL-1.0 \xc2\xa7""6, \xc2\xa7""8, \xc2\xa7""11\n"
        "  remediation:    restore LICENSE-SCSL-1.0.md from\n"
        "                  %s\n"
        "                  and run `make license-check`\n",
        rc, why, spektre_license_sha256_hex, SPEKTRE_SOURCE_URL);

    if (hard) {
        fprintf(stderr,
            "spektre-license-guard: aborting (set SPEKTRE_LICENSE_SOFT=1 to downgrade to warning)\n");
        exit(87);
    }
    return rc;
}
