#!/usr/bin/env bash
# Emit a local DO-178C-oriented evidence folder (not an authority certification).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/docs/do178c/evidence}"

mkdir -p "$OUT/lean_proofs" "$OUT/frama_c_proofs" "$OUT/test_results" "$OUT/receipts"

cp "$ROOT/docs/do178c/trace.csv" "$OUT/trace.csv"
cp "$ROOT/docs/do178c/traceability_matrix.md" "$OUT/traceability_matrix.md"
cp "$ROOT/docs/do178c/wcet_notes.md" "$OUT/wcet_notes.md"

if [[ -f "$ROOT/hw/formal/v259/Measurement.lean" ]]; then
  cp "$ROOT/hw/formal/v259/Measurement.lean" "$OUT/lean_proofs/" || true
fi
cp "$ROOT/benchmarks/v138/check_v138_prove_frama_c_wp.sh" "$OUT/frama_c_proofs/" || true

{
  echo "# Plan for Software Aspects of Certification (PSAC) — template"
  echo
  echo "This file is a **scaffold** generated by cos certify. It is not"
  echo "a PSAC accepted by any certification authority unless completed"
  echo "outside this repository."
  echo
  echo "Traceability seed: trace.csv in this directory."
} >"$OUT/PSAC.md"

{
  echo "# Software Development Plan (SDP) — template"
  echo
  echo "Pointer: repository \`Makefile\`, \`CONTRIBUTING.md\`, and"
  echo "\`docs/CLAIM_DISCIPLINE.md\` for evidence-class rules."
} >"$OUT/SDP.md"

{
  echo "# Software Verification Plan (SVP) — template"
  echo
  echo "Verification entrypoints: \`make merge-gate\`, \`make check-sigma-pipeline\`,"
  echo "and \`make verify-do178c\` (trace + lean discharge check + v138 formal probe)."
} >"$OUT/SVP.md"

{
  echo "# Software Accomplishment Summary (SAS) — template"
  echo
  echo "Populate with release-specific test logs and review sign-off."
} >"$OUT/SAS.md"

{
  echo "coverage-proof-receipt (optional):"
  echo "  make coverage-proof-receipt"
  echo "Then inspect proof_receipt.c.gcov in the build directory."
} >"$OUT/coverage.txt"

if compgen -G "$HOME/.cos/audit/"*.jsonl >/dev/null 2>&1; then
  cp "$HOME"/.cos/audit/*.jsonl "$OUT/receipts/" 2>/dev/null || true
fi

echo "do178c_certify: wrote evidence tree at $OUT"
